First pass at using folderfun
databio/projectInit pull request #22
Opened 2018-12-08 17:28 UTC by vreuter

Not sure this is ready for merge but am opening mostly to see if this is on the right track, @nsheff

2018-12-08 18:12 UTC, stolarczyk requested changes
I've deleted the `inff` function as suggested in https://github.com/databio/folderfun/issues/4. We'll need to use the `setff`, then.

2018-12-08 18:19 UTC, vreuter commented
:ok_hand: thanks @michalstolarczyk

2018-12-08 18:20 UTC, michalstolarczyk commented
```r
.getVar = function(name) {
  opt = getOption(name)
  if(!is.null(opt))
    return(opt)
  env = Sys.getenv(name)
  if(!identical("",env))
    return(env)
  return(NULL)
}

folderfun::setff("Proc",.getVar("PROCESSED.PROJECT"))
```

For example, this is how we could do it

2019-02-27 22:06 UTC, nsheff commented on DESCRIPTION
> +    databio/folderfun
can take this out soon... I've submitted folderfun to CRAN

2019-02-27 22:08 UTC, nsheff commented on R/dirAliases.R
> +dirOutRoot = function(...) ffROUT.DIR(...)
instead of this, let's just do:

`setff("OutRoot", "ROUT.DIR")`

and then use `ff` instead of `dir` from now on...

2019-02-27 22:09 UTC, nsheff commented
I'm going to merge this in and make some changes now...

2019-02-27 22:10 UTC, merged